server {
    # Escucha peticiones HTTP en el puerto 80
    listen 80;

    # Nombre del servidor/dominio
    server_name localhost;

    # Carpeta donde están los archivos estáticos del frontend
    root /usr/share/nginx/html;

    # Archivo por defecto al entrar al sitio
    index index.html;

    location / {
        # Intenta servir:
        # 1. el archivo solicitado
        # 2. el directorio solicitado
        # 3. si no existe, devuelve index.html
        # Esto es típico en aplicaciones SPA (React/Vue/Angular)
        try_files $uri $uri/ /index.html;
    }

    location /api/ {
        # Redirige todas las peticiones /api al backend
        proxy_pass http://backend:5000;

        # Envía el host original al backend
        proxy_set_header Host $host;

        # Envía la IP real del cliente al backend
        proxy_set_header X-Real-IP $remote_addr;
    }
}