version: '3.8'

services:
  api:
    build: .
    container_name: backend_moda_api
    # Aquí mapeamos el puerto externo 5002 al 5000 interno para que no choque con tu Flask local
    ports:
      - "5002:5000"
    # Aquí guardamos de forma fácil la configuración de la base de datos (el volumen)
    volumes:
      - ./app/moda_comercio.db:/app/app/moda_comercio.db
    # Reinicia el contenedor automáticamente si se cae por algún error
    restart: always